name = "61craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "623f4cf2ddf779665fb9f1d2cb5dde5666e1c28d520dcd80c80ae21030354bfe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
