name = "61craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a758b61c519cd734a4052cc0a4ca35be1a2a5f4b82951971c0848d6631ca4fdb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
